### Tutorial Numpy

Numpy é uma biblioteca para computação científica em Python. Ele fornece um objeto matriz multidimensional de alto desempenho, e ferramentas para trabalhar com essas matrizes. 

In [1]:
import numpy as np

#### Arrays

Um array numpy é uma grade de valores, todos do mesmo tipo, e é indexado por uma tupla de inteiros não-negativos. 
O número de dimensões é a classificação da matriz; 
a forma de uma matriz de inteiros é uma tupla dando o tamanho da matriz ao longo de cada dimensão.
Podemos inicializar matrizes Numpy a partir de listas Python aninhadas e elementos de acesso usando colchotes:

In [8]:
lista = [3,4,5,6]
array = np.array(lista)

print(lista)
print(array)
print(array.shape)
print(type(lista))
print(type(array))


[3, 4, 5, 6]
[3 4 5 6]
(4,)
<class 'list'>
<class 'numpy.ndarray'>


In [10]:
lista1 = [[1,2,3],[4,5,6]]
array1 = np.array(lista1)
print(lista1)
print(array1)
print(array1.shape)
print(type(array1))
print(type(lista1))


[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]
(2, 3)
<class 'numpy.ndarray'>
<class 'list'>


Numpy também nos fornece várias funções para criar arrays.

In [11]:
m = np.zeros((2,2))
print(m)

[[ 0.  0.]
 [ 0.  0.]]


In [13]:
m = np.ones((2,2))
print(m)

[[ 1.  1.]
 [ 1.  1.]]


In [15]:
m = np.full((2,2),7)
print(m)

[[7 7]
 [7 7]]


In [18]:
m = np.eye(5)
print(m)

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [24]:
m = np.random.random((2,2))
print(m)

[[ 0.33045945  0.8599509 ]
 [ 0.70536728  0.78354748]]


### Indexando Arrays

In [26]:
matriz = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(matriz)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [31]:
# Todas as linhas até a segunda
# da coluna 1 a 2
b = matriz[:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [34]:
print(matriz[0][1])
# ou
print(matriz[0,1])

2
2


In [37]:
#primeira linha e todas as colunas
linha1 = matriz[1,:]
print(linha1)


[5 6 7 8]


In [40]:
# indexando por pares 
# matriz[0][0], matriz[1][1], matriz[2][0]
print(matriz[[0, 1, 2], [0, 1, 0]]) 

[1 6 9]


In [41]:
print(matriz[matriz > 2])

[ 3  4  5  6  7  8  9 10 11 12]


### Operações Matemáticas
O Numpy nos oferece muitas facilidade no que diz respeito a operações com arrays multidimensionais. Por exemplo, podemos somar, multiplicar matrizes apenas com os operadores comuns de multiplicação e adição para números reais. Há uma sobrescrita de operador. Mostraremos abaixo, essas operações com objetos multidimensionais.

In [43]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [44]:
print("Matriz x")
print(x)
print("Matriz y")
print(y)

Matriz x
[[1 2]
 [3 4]]
Matriz y
[[5 6]
 [7 8]]


In [48]:
print(x-y)
print("Ou")
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]
Ou
[[-4 -4]
 [-4 -4]]


In [49]:
print(x * y)
print("Ou")
print(np.multiply(x, y))

[[ 5 12]
 [21 32]]
Ou
[[ 5 12]
 [21 32]]


In [50]:
print(x / y)
print("Ou")
print(np.divide(x, y))

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
Ou
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [51]:
print(np.sqrt(x))

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [54]:
print(x.dot(y))
print("Ou")
print(np.dot(x,y))

[[19 22]
 [43 50]]
Ou
[[19 22]
 [43 50]]


In [61]:
print("Matriz x")
print(x)
print("")
print("Transposta de x")
print(x.T)

Matriz x
[[1 2]
 [3 4]]

Transposta de x
[[1 3]
 [2 4]]
