In [1]:
from sklearn.model_selection import train_test_split
import numpy as np

In [3]:
X = np.arange(10)
y = np.concatenate((np.zeros((1,5)),np.ones((1,5))) , axis=1 )[0]

In [4]:
X,y

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.]))

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.4, random_state=3)

In [12]:
X_train, X_test, y_train, y_test

(array([9, 6, 7, 0, 3, 8]),
 array([5, 4, 1, 2]),
 array([1., 1., 1., 0., 0., 1.]),
 array([1., 0., 0., 0.]))

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.4, stratify=y)

In [14]:
X_train, X_test, y_train, y_test

(array([2, 5, 9, 4, 3, 6]),
 array([1, 0, 8, 7]),
 array([0., 1., 1., 0., 0., 1.]),
 array([0., 0., 1., 1.]))