# Introdução ao Numpy

Numpy é uma biblioteca para computação científica em Python. 
Ele fornece um objeto matriz multidimensional de alto desempenho, e ferramentas para trabalhar com essas matrizes.

- É muito mais eficiente que as estruturas nativas do Python para manipulação de dados numéricos.
- Em sua maioria é implementado na linguagem C.
- A maior parte das bibliotecas de análise e manipulação de dados em Python usam o Numpy.
- Mesmo que você use bibliotecas de mais alto nível, mais cedo ou mais tarde, você certamente precisará usar o Numpy.


In [1]:
import numpy as np

## Arrays de n-dimensões (ndarray)

### 1 dimensão

In [37]:
a1 = np.array([1, 2, 3])
print(a1)

[1 2 3]


In [38]:
a1.shape

(3,)

In [97]:
a1.ndim

1

In [66]:
a1.dtype

dtype('int64')

### 2 dimensões

In [39]:
a2 = np.array([(1.5, 2, 3), (4, 5, 6), (1, 0, 1)], dtype = float)
print(a2)

[[ 1.5  2.   3. ]
 [ 4.   5.   6. ]
 [ 1.   0.   1. ]]


In [40]:
a2.shape

(3, 3)

In [98]:
a2.ndim

2

In [65]:
a2.dtype

dtype('float64')

##### Obtendo linha

In [95]:
a2[1, :]

array([ 4.,  5.,  6.])

##### Obtendo coluna

In [96]:
a2[:, 1]

array([ 2.,  5.,  0.])

### 3 dimensões

In [53]:
# pensar em camadas
a3 = np.array([ [(5, 2, 1, 4), (4, 5, 6, 5), (1, 2, 3, 4)], 
                [(3, 2, 1, 6), (6, 5, 4, 7), (3, 2, 1, 4)]], dtype = float)
print(a3)

[[[ 5.  2.  1.  4.]
  [ 4.  5.  6.  5.]
  [ 1.  2.  3.  4.]]

 [[ 3.  2.  1.  6.]
  [ 6.  5.  4.  7.]
  [ 3.  2.  1.  4.]]]


In [54]:
a3.shape

(2, 3, 4)

In [99]:
a3.ndim

3

In [67]:
a3.dtype

dtype('float64')

In [70]:
a3[0, 1, 2]

6.0

### Tipos de dados

In [92]:
np.int64    # Signed 64-bit integer types
np.float64  # Standard double-precision floating point
np.complex  # Complex numbers represented by 128 floats
np.bool     # Boolean type storing TRUE and FALSE values
np.object   # Python object type
np.string_  # Fixed-length string type
np.unicode_ # Fixed-length unicode type

numpy.str_

### Conversão de Tipos

In [81]:
a3_nova = a3.astype('int64')
print(a3_nova)

[[[5 2 1 4]
  [4 5 6 5]
  [1 2 3 4]]

 [[3 2 1 6]
  [6 5 4 7]
  [3 2 1 4]]]


In [83]:
a3_nova.dtype

dtype('int64')

### Criação de arrays "especiais"

#### Vazio

In [64]:
np.empty((3, 4))  # não atribui valores zero aos elementos da matriz. é rápido. 
# usar quando for necessário atribuir todos os valores. 

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

#### Zeros

In [63]:
c = np.zeros((3, 4)) # array de zeros
print(c)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


#### 1s

In [19]:
np.ones((2, 3, 4),dtype=np.int16) # array de 1s

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

#### Valores espaçados

In [29]:
# arange([start,] stop[, step,], dtype=None)
np.arange(0, 10, 5)        # array de valores espaçados. baseado no passo (intervalo) entre os números.

array([0, 5])

In [30]:
# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
np.linspace(0, 10, 5)        # array de valores espaçados. baseado na qtd total de elementos.

array([  0. ,   2.5,   5. ,   7.5,  10. ])

#### Valores constantes

In [56]:
np.full((2,2),7) # Create a constant array

array([[7, 7],
       [7, 7]])

#### Matriz identidade

In [86]:
np.eye(2)  # Create a 2X2 identity matrix
# np.identity(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

#### Matriz com valores randômicos

In [87]:
np.random.random((3, 3)) # entre 0 e 1

array([[ 0.07387827,  0.97450391,  0.6737696 ],
       [ 0.02019044,  0.20490744,  0.37352166],
       [ 0.92875773,  0.06228969,  0.34996895]])

In [90]:
r1 = np.random.random((3, 3)) * 10 # entre 0 e 10 (float)
print(r1)

[[ 9.59623369  8.45273253  2.33213659]
 [ 7.13089777  0.10765659  1.9820133 ]
 [ 7.71760252  6.74731001  7.9182123 ]]


In [91]:
r1.dtype

dtype('float64')

In [93]:
r2 = np.random.randint(1, 10,size=(3, 3)) # entre 1 e 10 (inteiros)
print(r2)

[[7 4 6]
 [2 2 4]
 [3 8 6]]


In [94]:
r2.dtype

dtype('int64')