# Divisão estratificada do conjunto de dados em conjunto de treino e conjunto de teste

Durante a fase de treino de um modelo em aprendizado de máquina é muito importante que possamos usar o máximo de dados disponíveis para realizar o treino deste modelo, assim o algoritmo, com mais dados, vai aprender melhor e fica mas fácil a predição dos valores.

In [1]:
from sklearn.model_selection import train_test_split
import numpy as np

Aqui vamos gerar uns valores de X e y para teste e explicação do exemplo.

In [2]:
X = np.arange(10)
y = np.concatenate((np.zeros((1,5)), np.ones((1,5))), axis=1)[0]

In [3]:
X, y

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.]))

   Perceba que nas linhas abaixo é feita apenas a  divisão dos dados sem qualquer critério, assim o vetor resultante tem mais valores 1 no y_train do que 0, isso se torna desvantajoso, pois para o modelo fica difícil identificar os valores 0, já que ele não tem muito conhecimento do próprio. Perceba também que no y_test temos mas valores 0 do que 1, isso resulta e uma má predição para o modelo, pois com pouco conhecimento nesses valores 0 o modelo pode acabar dizendo que um dado valor 0 é 1.

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=3)

In [5]:
X_train, X_test, y_train, y_test

(array([9, 6, 7, 0, 3, 8]),
 array([5, 4, 1, 2]),
 array([1., 1., 1., 0., 0., 1.]),
 array([1., 0., 0., 0.]))

Neste exemplo foi pedido para o algoritmo de divisão que ele realiza a estratificação dos dados para o vetor y, ou seja neste caso ele vai tentar manter a porcentagem dos valores certas para os dados valores diferentes que estão presentes no y, ou seja, como o teste foi definido como 40% do vetor de y, então 40% dos valores de 1 e 0 estarão no vetor de y_test e os outros 60% estarão no vetor de y_train, Como demonstrado no exemplo abaixo.

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, stratify=y)

In [7]:
X_train, X_test, y_train, y_test

(array([4, 7, 1, 8, 5, 0]),
 array([6, 9, 2, 3]),
 array([0., 1., 0., 1., 1., 0.]),
 array([1., 1., 0., 0.]))