In [1]:
a = [1,2,3,4,5]

In [2]:
a


[1, 2, 3, 4, 5]

In [3]:
import numpy as np

In [4]:
np.array(a)

array([1, 2, 3, 4, 5])

In [5]:
b = [[1,2,3], [4,5,6]]

In [6]:
b

[[1, 2, 3], [4, 5, 6]]

In [7]:
np.array(b)

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones( (3,4) )

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.ones( (2,3,4) )

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [11]:
np.empty( (2,3) )

array([[6.93544231e-310, 4.66149173e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [12]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [16]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [17]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])