In [1]:
import numpy as np

In [2]:
a = np.array([20,30,40,50])

In [3]:
b = np.arange(4)

In [4]:
a

array([20, 30, 40, 50])

In [5]:
b

array([0, 1, 2, 3])

In [6]:
a-b

array([20, 29, 38, 47])

In [7]:
b**2

array([0, 1, 4, 9])

In [8]:
np.sin(a)

array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [9]:
a<35

array([ True,  True, False, False])

In [10]:
A = np.array([[1,1],[0,1]])

In [11]:
B = np.array([[2,0],[3,4]])

In [12]:
A

array([[1, 1],
       [0, 1]])

In [13]:
B

array([[2, 0],
       [3, 4]])

In [14]:
A*B

array([[2, 0],
       [0, 4]])

In [15]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [16]:
np.dot(A,B)

array([[5, 4],
       [3, 4]])

In [17]:
A *= 3

In [18]:
A

array([[3, 3],
       [0, 3]])

In [19]:
A += 3

In [26]:
A

array([[6, 6],
       [3, 6]])

In [27]:
A += B

In [28]:
A

array([[ 8,  6],
       [ 6, 10]])

In [29]:
A.sum()

30

In [30]:
A.min()

6

In [31]:
A.max()

10

In [33]:
A[1,:]

array([ 6, 10])

In [34]:
A[0,:]

array([8, 6])

In [35]:
A[:,0]

array([8, 6])